name: Update Root-Me Badge

on:
  schedule:
    - cron: "0 0 * * *"  # Mise à jour quotidienne
  workflow_dispatch:  # Permet d'exécuter manuellement

permissions:
  contents: write  # Autorise l'écriture dans le repo

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pillow requests

      - name: Run Python script
        run: python generate_rootme_badge.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add rootme_score.png
          git commit -m "Mise à jour du badge Root-Me" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
